# Generated by Django 6.0.6 on 2026-07-19 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberprofile",
            name="trainer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="gym.trainer",
            ),
        ),
        migrations.AlterField(
            model_name="trainer",
            name="shift_timings",
            field=models.TimeField(),
        ),
    ]
