# Generated by Django 5.2.7 on 2026-07-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainer",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="trainer",
            name="updated_at",
        ),
    ]
