# Generated by Django 5.2.7 on 2026-07-28 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0002_alter_memberprofile_trainer_and_more"),
        ("gym", "0002_remove_trainer_created_at_remove_trainer_updated_at"),
    ]

    operations = []
