# Generated by Django 5.2.7 on 2026-07-28 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0003_merge_20260729_0007"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietplan",
            name="protein_goal",
            field=models.PositiveIntegerField(
                default=0, help_text="Daily protein goal in grams"
            ),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="assigned_trainer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enquiries",
                to="gym.trainer",
            ),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="follow_up_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="reply",
            field=models.TextField(blank=True, help_text="Admin reply to enquiry"),
        ),
        migrations.AddField(
            model_name="equipment",
            name="condition",
            field=models.CharField(
                choices=[("GOOD", "Good"), ("FAIR", "Fair"), ("DAMAGED", "Damaged")],
                default="GOOD",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="equipment/"),
        ),
        migrations.AddField(
            model_name="equipment",
            name="maintenance_date",
            field=models.DateField(
                blank=True, help_text="Next scheduled maintenance", null=True
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="warranty_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trainer",
            name="bio",
            field=models.TextField(blank=True, help_text="Short trainer bio"),
        ),
        migrations.AddField(
            model_name="workoutplan",
            name="calories_burned",
            field=models.PositiveIntegerField(
                default=0, help_text="Estimated calories burned"
            ),
        ),
        migrations.AddField(
            model_name="workoutplan",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("BEGINNER", "Beginner"),
                    ("INTERMEDIATE", "Intermediate"),
                    ("ADVANCED", "Advanced"),
                ],
                default="BEGINNER",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workoutplan",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                default=30, help_text="Duration in minutes"
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="dietplan",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="memberprofile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="membershipplan",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="otp",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="trainer",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="workoutplan",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "notif_type",
                    models.CharField(
                        choices=[
                            ("EXPIRY", "Membership Expiry"),
                            ("BIRTHDAY", "Birthday Wish"),
                            ("PAYMENT", "Payment Due"),
                            ("ANNOUNCEMENT", "Announcement"),
                            ("GENERAL", "General"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank to send to all members",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="gym.memberprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
