# Generated by Django 5.2.7 on 2026-07-28 20:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0004_dietplan_protein_goal_enquiry_assigned_trainer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ANNOUNCEMENT", "General Announcement"),
                            ("OFFER", "Special Offer"),
                            ("HOLIDAY", "Gym Holiday"),
                            ("EVENT", "Special Event"),
                        ],
                        default="ANNOUNCEMENT",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="announcements/"
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Announcement",
                "verbose_name_plural": "Announcements",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GalleryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GYM_PHOTO", "Gym Infrastructure"),
                            ("EVENT", "Gym Event"),
                            ("TRANSFORMATION", "Member Transformation"),
                            ("VIDEO", "Video Highlight"),
                        ],
                        default="GYM_PHOTO",
                        max_length=30,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="gallery/"),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True, help_text="Video link if category is Video"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Gallery Item",
                "verbose_name_plural": "Gallery Items",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="membershipplan",
            options={
                "ordering": ["price"],
                "verbose_name": "Membership Plan",
                "verbose_name_plural": "Membership Plans",
            },
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="last_service_date",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="next_service_date",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="warranty_months",
        ),
        migrations.AddField(
            model_name="equipment",
            name="brand",
            field=models.CharField(
                blank=True, help_text="e.g. Life Fitness, Rogue", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="category",
            field=models.CharField(
                default="Strength",
                help_text="Cardio, Strength, Accessories, etc.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="location",
            field=models.CharField(
                blank=True, default="Main Gym Floor", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="model_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="equipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("MAINTENANCE", "Under Maintenance"),
                    ("RETIRED", "Retired"),
                ],
                default="AVAILABLE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="memberprofile",
            name="fitness_goal",
            field=models.CharField(
                choices=[
                    ("WEIGHT_LOSS", "Weight Loss"),
                    ("MUSCLE_GAIN", "Muscle Gain"),
                    ("MAINTENANCE", "Fitness & Maintenance"),
                ],
                default="WEIGHT_LOSS",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="memberprofile",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
        ),
        migrations.AddField(
            model_name="membershipplan",
            name="access_time",
            field=models.CharField(default="6:00 AM - 10:00 PM", max_length=100),
        ),
        migrations.AddField(
            model_name="membershipplan",
            name="benefits",
            field=models.TextField(
                blank=True, help_text="Commas or line-separated benefits list"
            ),
        ),
        migrations.AddField(
            model_name="membershipplan",
            name="diet_plan_included",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="membershipplan",
            name="tier",
            field=models.CharField(
                choices=[
                    ("SILVER", "Silver"),
                    ("GOLD", "Gold"),
                    ("PLATINUM", "Platinum"),
                    ("PREMIUM", "Premium"),
                ],
                default="GOLD",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="membershipplan",
            name="trainer_included",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="otp",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("REGISTER", "Registration Verification"),
                    ("FORGOT_PASSWORD", "Password Reset"),
                ],
                default="REGISTER",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_proof",
            field=models.ImageField(blank=True, null=True, upload_to="payment_proofs/"),
        ),
        migrations.AddField(
            model_name="trainer",
            name="certifications",
            field=models.TextField(
                blank=True, help_text="Certified Personal Trainer, Crossfit, etc."
            ),
        ),
        migrations.AddField(
            model_name="trainer",
            name="weekly_schedule",
            field=models.TextField(
                blank=True, help_text="Mon-Fri 6am-2pm, Sat 8am-12pm"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="account_locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="failed_login_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="workoutplan",
            name="equipment_required",
            field=models.CharField(
                blank=True, default="Dumbbells / Barbell", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="workoutplan",
            name="exercise_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="workout_exercises/"
            ),
        ),
        migrations.AddField(
            model_name="workoutplan",
            name="video_url",
            field=models.URLField(
                blank=True, help_text="YouTube or Vimeo demonstration video link"
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="condition",
            field=models.CharField(
                choices=[
                    ("EXCELLENT", "Excellent"),
                    ("GOOD", "Good"),
                    ("FAIR", "Fair"),
                    ("DAMAGED", "Damaged"),
                ],
                default="GOOD",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name="MemberProgressHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, help_text="Weight in kg", max_digits=5
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=2, help_text="Height in cm", max_digits=5
                    ),
                ),
                ("bmi", models.DecimalField(decimal_places=2, max_digits=5)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_history",
                        to="gym.memberprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Member Progress History",
                "verbose_name_plural": "Member Progress Histories",
                "ordering": ["date"],
            },
        ),
    ]
