# Generated by Django 5.2.7 on 2026-07-30 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0005_announcement_galleryitem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("REGISTER", "Registration Verification"),
                    ("FORGOT_PASSWORD", "Password Reset"),
                    ("ADMIN_LOGIN", "Admin Login Verification"),
                ],
                default="REGISTER",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="LoginVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="live_verifications/")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Login Verification",
                "verbose_name_plural": "Login Verifications",
                "ordering": ["-timestamp"],
            },
        ),
    ]
